name: RCES_Final
channels:
  - defaults
dependencies:
  - python=3.6
  - cartopy
  - matplotlib
  - numpy
  - pandas
  - pyproj
  - rasterio
  - s3fs
  - s3transfer
  - scikit-learn
  - scipy
  - xarray
